### ISSUE TITLE
Benchmarking broken due to changes in easybench fork

### ISSUE THREAD

**Issue by lasa01** [droundy/tinyset#12]
Trying to run `cargo bench` produces the following error:
```
cargo bench
    Updating crates.io index
    Updating git repository `https://github.com/droundy/easybench-rs`
error: no matching package named `easybench` found
location searched: https://github.com/droundy/easybench-rs
required by package `tinyset v0.4.4 (D:\lasa\Code\tinyset)`
```

This seems to be because of the package name change and renamed functions in your fork. 

Changing the dependency to `easybench = { version = "1.0.0", git = "https://github.com/droundy/easybench-rs", rev = "0e4418659ab2695ea68415037b2d59c53744f73e" }
` fixes it.

**Comment by droundy** [comment]
Thanks for the bug report!
