### ISSUE TITLE
Elements order?

### ISSUE THREAD

**Issue by tower120** [droundy/tinyset#17]
Is it guaranteed that elements iterated/stored in ascending order?

```rust
assert( tinyset.iter().is_sorted() );
```

**Comment by droundy** [comment]
No, they will often be in a somewhat randomized order.

**Comment by tower120** [comment]
"somewhat randomized order" - means that it consists from ordered/sorted spans, but these spans may be not ordered between each other?

**Comment by droundy** [comment]
It means it depends on how many items are in your set and how big they are and how densely packed they are. Also the history in which they were added and removed.  They may come out entirely ordered or partially ordered or possibly not at all.

**Comment by tower120** [comment]
Oh, I see. Thank you for explanation!

I just did some smoke tests, and was under impression, that `tinyset` store elements like `Vec<Vec<usize>>` but sorted. And then do some kind of binary lookup.
