### ISSUE TITLE
`dense_with_max()` and `with_capacity_and_bits()` write to null pointer on OOM

### ISSUE THREAD

**Issue by LegionMammal978** [droundy/tinyset#18]
`SetU32::dense_with_max()`, `SetU32::with_capacity_and_bits()`, `SetU64::dense_with_max()`, and `SetU64::with_capacity_and_bits()` call `alloc_zeroed()` to allocate memory, but do not check if the returned pointer is null before writing to it. This results in a segmentation fault if the allocation fails.

```rust
/*
[dependencies]
tinyset = "=0.4.14"
*/

use tinyset::SetU32;

fn main() {
    SetU32::with_capacity_and_bits(usize::MAX / 8 - 2, 0);
    // Segmentation fault (core dumped)
}
```

**Comment by droundy** [comment]
Thanks so much for the report, I fixed this a week ago and apparently forgot to close it.  I still need to make a release.
