### ISSUE TITLE
Map64 and Map6464 are not exported

### ISSUE THREAD

**Issue by mateon1** [droundy/tinyset#7]
The map64 module is private, and the Map64 types are not exported. The README is currently wrong, as it documents these types as if they were accessible.
Please either re-export the types or update the readme.

**Comment by droundy** [comment]
They shouldn't be mentioned in the readme sorry about that.

**Comment by droundy** [comment]
I'll yet to get to fixing this probably in the summer after a quarter of teaching remotely.
